### PR TITLE
Copy scalastyle-config.xml from circe/circe

### PR DESCRIPTION
**Pull request by n4to4**
See
https://github.com/circe/circe-jackson/pull/10
https://github.com/circe/circe-spray/pull/1

### CODE REVIEW

**Comment by jensraaby** [comment]
Thanks @n4to4. This looks fine to merge.

I'm curious whether it would work to have 1 copy of the Scalastyle XML and reference it across the projects? (See http://www.scalastyle.org/sbt.html - "scalastyleConfigUrl")
I haven't seen many teams actually doing this across their repos before, but it might be nicer to have one place to change the config instead of several. 
On the other hand, I doubt this is particularly frequently changing config.
Any thoughts @travisbrown ?

**Comment by n4to4** [comment]
Maybe by using [git submodule](https://git-scm.com/docs/git-submodule)? (I haven't tried it though)
Or it might be useful to have an [sbt template](http://www.scala-sbt.org/0.13/docs/sbt-new-and-Templates.html) repository.

**Comment by travisbrown** [comment]
I think the best route if we decide that maintaining separate builds is too much work would be something like Scodec's [scodec-build](https://github.com/scodec/scodec-build). So far I'm not quite convinced it's worth the trouble, even with things like Scalastyle config (which very rarely changes).

**Comment by travisbrown** [comment]
I just tried out GitHub's new-ish in-browser conflict resolver thing—once this is green I'll merge.

**Pull request closed without merging**
